[package]
name = "trustdidweb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = { version = "0.26.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "bbscryptosuite"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"