[package]
name = "didtoolbox"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = { version = "0.26.1", features = ["cli"] }
serde = {version = "1.0.202", features = ["derive"]}
serde_json = {version = "1.0.117", features = ["preserve_order"]}
serde_jcs = "0.1.0"
chrono = {version = "0.4.38", features = ["serde"]}
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8.5"
base64 = "0.22.1"
rstest = "0.19.0"
sha2 = "0.10.8"
hex-literal = "0.4.1"
hex = "0.4.3"
base32 = "0.5.0"
regex = "1.10.4"
ureq = "2.9.7"
url-escape = "0.1.1"

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "didtoolbox"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"